import type { ReactNode } from "react";

export function ReportShell({
  title,
  companyName,
  periodLabel,
  generatedLabel,
  children,
}: {
  title: string;
  companyName?: string;
  periodLabel: string;
  generatedLabel: string;
  children: ReactNode;
}) {
  return (
    <main className="report-document min-h-screen h-dvh overflow-y-auto bg-slate-100 px-4 py-8 text-slate-950 sm:px-8">
      <div className="report-page mx-auto max-w-6xl bg-white px-8 py-10 shadow-sm sm:px-12">
        <header className="report-header mb-8 border-b border-slate-200 pb-6">
          <div className="flex items-start justify-between gap-8">
            <div>
              <div className="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">
                Ser3bellum
              </div>

              <h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">
                {title}
              </h1>

              {companyName ? (
                <p className="mt-2 text-base font-medium text-slate-700">
                  {companyName}
                </p>
              ) : null}
            </div>

            <div className="text-right text-xs leading-5 text-slate-500">
              <div>{periodLabel}</div>
              <div>{generatedLabel}</div>
            </div>
          </div>
        </header>

        {children}

        <footer className="report-footer mt-10 border-t border-slate-200 pt-4 text-xs text-slate-400">
          Generated by Ser3bellum · One dashboard. Zero guesswork.
        </footer>
      </div>
    </main>
  );
}